name: Build

on: 
  push:
    branches:
      - main
      - 'dev-*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v6
      with:
        node-version: current

    - run: npx vsce package

    - uses: actions/upload-artifact@v4
      with:
        path: okayu-theme-*.vsix
